<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ps2.Core\Ps2.Core.csproj" />
    <ProjectReference Include="..\Ps2.Parser\Ps2.Parser.csproj" />
    <ProjectReference Include="..\Ps2.Runtime\Ps2.Runtime.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
